export {
  cleanBlogTitleForAlt,
  generateBlogCoverAltText,
  getBlogImageAltText,
  type BlogCoverAltTextInput,
} from "./blogAltText";

/** Shared image metadata for optimized responsive site photography. */
const RESPONSIVE_IMAGE_HEIGHTS: Readonly<Record<string, number>> = {
  "airport_departure_board_delay_claim_1790520824658": 670,
  "bangkok_destination_1781544149435": 655,
  "bangkok_medical_hospital_lobby_1790520775439": 670,
  "bangkok_wat_arun_chao_phraya_1790486821534": 670,
  "bangladesh_epassport_biometric_desk_1790520813052": 670,
  "bdt_travel_concierge_voucher_1790486777146": 670,
  "blog_editorial_hero_banner_1790429994056": 670,
  "clouds_boat_hero_1781438671378": 670,
  "coxs_bazar_sunrise_1781620718331": 670,
  "dhaka_airport_widebody_airlines_tarmac_1790520836931": 670,
  "dubai_destination_1781544180311": 655,
  "dubai_skyline_burj_twilight_1790485747967": 670,
  "haramain_bullet_train_1790484312808": 896,
  "ihram_preparation_set_1790484426740": 896,
  "islamic_banking_card_makkah_1790486749439": 670,
  "jeddah_airport_terminal_1790484400414": 896,
  "kl_destination_1781544164707": 655,
  "kuala_lumpur_petronas_twilight_1790486835902": 670,
  "madinah_courtyard_umbrellas_1790484340720": 896,
  "madinah_green_dome_1790484369923": 896,
  "makkah_halal_cuisine_1790484456326": 896,
  "maldives_destination_1790387286896": 896,
  "masjid_nabawi_arches_1790484388265": 896,
  "mina_hajj_tents_1790484325661": 896,
  "nepal_destination_1781544132297": 655,
  "paris_louvre_london_landmarks_1790485782111": 670,
  "passport_card_travel_desk_1790430035290": 896,
  "passport_stamps_boarding_window_1790486849797": 670,
  "pos_card_terminal_currency_1790486792551": 670,
  "putrajaya_pink_mosque_malaysia_1790485770212": 670,
  "quba_mosque_taif_ziyarah_1790485732985": 670,
  "ramadan_makkah_night_1790484415220": 896,
  "rfcd_foreign_currency_banking_1790486762760": 670,
  "saudi_stopover_aircraft_1790484351784": 896,
  "sheikh_zayed_grand_mosque_1790485758750": 670,
  "singapore_destination_1790387270177": 896,
  "singapore_mrt_gardens_bay_1790520762227": 670,
  "sri_lanka_nine_arch_train_1790520800518": 670,
  "travel_esim_smartphone_insurance_1790520786938": 670,
  "umrah_makkah_haram_guide_1790430007679": 896,
  "ural_hero_bg_1781543111624": 670,
  "zamzam_ajwa_dates_1790484440926": 896,
};

const RESPONSIVE_IMAGE_WIDTH = 1200;

/**
 * The responsive breakpoints generated by scripts/optimize-images-production.sh.
 * 960w was added because the old 640/1200 pair left a gap exactly where most
 * traffic sits: a DPR-2 phone (390 CSS px → ~780 device px) and any tablet both
 * resolved to the 1200w file. With 960w in the set they download ~35% fewer
 * bytes for the same perceived quality.
 */
export const RESPONSIVE_IMAGE_BREAKPOINTS = [640, 960, 1200] as const;

/**
 * Build the `srcset`/`imagesrcset` value for a `-1200.webp` URL across every
 * generated breakpoint. Single source of truth: used by React (`getResponsiveImageProps`)
 * AND by scripts/prerender.ts when it rewrites the LCP `<link rel="preload">`
 * of all ~155 prerendered routes. Adding a breakpoint here updates both, which
 * is the whole point — the 2026-10 Google Fonts incident happened because one
 * copy of a value drifted from another.
 *
 * NOTE: index.html carries a hand-written copy of this string for the SPA
 * shell (static HTML cannot import TS). Keep it in sync; verify-build.ts
 * asserts that all three agree.
 */
export function buildResponsiveSrcSet(
  src1200: string,
  ext: "webp" | "avif" = "webp",
): string {
  return RESPONSIVE_IMAGE_BREAKPOINTS.map(
    (w) => `${src1200.replace(/-1200\.webp$/, `-${w}.${ext}`)} ${w}w`,
  ).join(", ");
}

export interface ResponsiveImageProps {
  src: string;
  srcSet: string;
  sizes: string;
  width: number;
  height: number;
}

/**
 * Normalise a photo URL to its 1200px canonical form and look up the intrinsic
 * dimensions used for `width`/`height` (which is what reserves space before the
 * image loads). Shared by `getResponsiveImageProps` and the `<ResponsiveImage>`
 * component so the dimension table has exactly one reader.
 */
export function getResponsiveImageDimensions(source: string): {
  src: string;
  width: number;
  height: number;
} {
  const src = source.replace(/-640\.webp$/, "-1200.webp");
  const baseName = src.split("/").pop()?.replace(/-1200\.webp$/, "") ?? "";
  const height = RESPONSIVE_IMAGE_HEIGHTS[baseName];
  if (!height) {
    throw new Error(`Missing intrinsic dimensions for optimized image: ${baseName}`);
  }

  return { src, width: RESPONSIVE_IMAGE_WIDTH, height };
}

/**
 * Return matching 640px/960px/1200px WebP sources and the 1200px file's
 * intrinsic dimensions. Keeping width and height in markup reserves the
 * correct space before the image loads; callers choose loading/fetch-priority
 * per context.
 *
 * Since the AVIF rollout this is the WebP-only path used by non-React callers
 * (scripts/prerender.ts builds the LCP preload from it) and by tests. React
 * call sites use `<ResponsiveImage>` in src/components/ResponsiveImage.tsx,
 * which wraps both formats in a <picture>. Do not add new call sites here.
 */
export function getResponsiveImageProps(
  source: string,
  sizes = "100vw",
): ResponsiveImageProps {
  const { src, width, height } = getResponsiveImageDimensions(source);

  return {
    src,
    srcSet: buildResponsiveSrcSet(src),
    sizes,
    width,
    height,
  };
}
